#!/usr/bin/env tsx
/**
 * Build-time embed: reads `llms.txt` and `llms-full.txt` from the repo root
 * and writes them as TypeScript string constants into
 * `src/sdk-context.generated.ts`. This lets the MCP server return SDK
 * context without filesystem access at runtime — important because MCP
 * servers run from `dist/` and locating the source files relative to the
 * compiled bundle is brittle.
 *
 * Run automatically via the `prebuild` npm script. Manual invocation:
 *   npx tsx scripts/embed-sdk-context.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../..');
const out = resolve(here, '../src/sdk-context.generated.ts');

function loadOrEmpty(path: string): string {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    console.warn(`[embed-sdk-context] missing: ${path} — embedding empty string`);
    return '';
  }
}

const llmsTxt = loadOrEmpty(resolve(repoRoot, 'llms.txt'));
const llmsFullTxt = loadOrEmpty(resolve(repoRoot, 'llms-full.txt'));

// Use String.raw + escape ${ and ` so a literal backtick or template-string
// inside the docs doesn't break the generated file.
function asTemplateLiteral(content: string): string {
  return content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

const generated = `// THIS FILE IS AUTO-GENERATED BY scripts/embed-sdk-context.ts
// Do not edit by hand. Source: <repo-root>/llms.txt and <repo-root>/llms-full.txt.
// Regenerate via \`npm run build\` (runs the prebuild hook).

/* eslint-disable */

/** Curated index of SDK docs (per https://llmstxt.org spec). */
export const LLMS_TXT = \`${asTemplateLiteral(llmsTxt)}\`;

/** Long-form embedded SDK context — modules, types, workflows, gotchas. */
export const LLMS_FULL_TXT = \`${asTemplateLiteral(llmsFullTxt)}\`;

/** Bytes of llms-full.txt; lets callers preview the size before requesting. */
export const LLMS_FULL_TXT_BYTES = ${Buffer.byteLength(llmsFullTxt, 'utf8')};
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, generated, 'utf8');
console.log(
  `[embed-sdk-context] wrote ${out} (${(Buffer.byteLength(generated, 'utf8') / 1024).toFixed(1)} KiB)`,
);
